port: 24110

db:
  username: "postgres"
  password: "postgres"
  host:     "localhost"
  port:     "5432"
  dbname:   "distcomp"
  sslmode:  "disable"

kafka:
  host: "localhost"
  port: "9092"

redis:
  host: "localhost"
  port: "6379"